root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 500 # Mempercepat waktu penundaan build ulang
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = [
	"go",
	"tpl",
	"tmpl",
	"html",
] # Pastikan ekstensi yang diinginkan disertakan
include_file = []
kill_delay = "0s"
log = "build-errors.log" # Log error build dicatat di file ini
poll = true # Mengaktifkan polling untuk memantau perubahan file
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false    # Menampilkan log
time = true       # Menampilkan waktu log

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
